query GetComments ($query:CommentsQueryArgs!,$option:PaginateOptionArgs!){
  getComments(query:$query, option:$option){
    docs{
      replyCount
      id
      post_id
      __typename
       body
       createdAt
       updatedAt
       isPostOwner
       isOwnComment
       isEdited
       isLiked
       depth
       likesCount
       author{
        id
        username
        avatar{
          avatarUrl
          avatarPublicId
          __typename
        }
       }
    }
    __typename
    totalDocs
    limit
    page
    totalPages
    hasNextPage
    hasPrevPage
    nextPage
    prevPage
    pagingCounter
  }
}