query GetRepliesComment ($query:ReplyQueryArgs!,$option:PaginateOptionArgs!){
  getReplies(query: $query,option: $option){
   docs{
      photos{
        photosUrl
        photosPublicId
        __typename
      }
      replyCount
      id
      post_id
      __typename
       body
       createdAt
       updatedAt
       author{
        id
        username
        email
        avatar{
          avatarUrl
          avatarPublicId
          __typename
        }
        name
       }
    }
    __typename
    totalDocs
    limit
    page
    totalPages
    hasNextPage
    hasPrevPage
    nextPage
    prevPage
    pagingCounter
  }
}