query GetRepliesComment($query: ReplyQueryArgs!, $option: PaginateOptionArgs!) {
  getReplies(query:$query , option:$option) {
    docs {
      replyCount
      id
      post_id
      __typename
      body
      createdAt
      updatedAt
      isPostOwner
      isOwnComment
      isEdited
      depth
      isLiked
      likesCount
      author {
        id
        username
        avatar {
          avatarUrl
          avatarPublicId
          __typename
        }
      }
    }
    __typename
    totalDocs
    limit
    page
    totalPages
    hasNextPage
    hasPrevPage
    nextPage
    prevPage
    pagingCounter
  }
}
