query GetNotifications ($query: NotificationQueryArgs! ,$options:PaginateOptionArgs!){
  getNotifications(query: $query,options: $options){
    docs{
      type
      id
      target{
        username
        avatar{
           avatarUrl
           avatarPublicId
        }
        name
        __typename

      }
      initiator{
        username
        avatar{
           avatarUrl
           avatarPublicId
        }
        name
        __typename
      }
      unread
      link
      createdAt
      updatedAt
      __typename
    }
  }
}