export const metaKeywords = [
  "Islamic community",
  "Social networking",
  "Muslim connections",
  "Faith-based platform",
  "Halal networking",
  "Ummah unity",
  "Islamic values",
  "Muslim friendships",
  "Online Muslim community",
  "Islamic networking",
  "Muslim professionals",
  "Quran study groups",
  "Islamic knowledge sharing",
  "Islamic events",
  "Prayer reminders",
  "Islamic discussions",
  "Islamic blogosphere",
  "Muslim lifestyle",
  "Islamic education",
  "Islamic charity",
  "Islamic news",
  "Muslim parenting",
  "Islamic business networking",
  "Islamic marriage",
  "Islamic finance",
  "Islamic art and culture",
  "Muslim scholars",
  "Islamic resources",
  "Islamic podcasts",
  "Islamic book club",
  "Islamic volunteering",
  "Muslim travel",
  "Islamic fashion",
  "Muslim health and wellness",
  "Islamic entrepreneurship",
  "Islamic media",
  "Islamic technology",
  "Islamic spirituality",
  "Islamic lectures",
  "Islamic history",
  "Islamic charity projects",
  "Islamic counseling",
  "Islamic youth",
  "Islamic philosophy",
  "Islamic festivals",
  "Islamic literature",
  "Islamic architecture",
  "Islamic sciences",
  "Islamic ethics",
  "Islamic politics",
  "Islamic activism",
  "Islamic research",
  "Islamic community development",
  "Islamic food and recipes",
  "Islamic women empowerment",
  "Islamic environment conservation",
  "Islamic language learning",
  "Islamic storytelling",
  "Islamic interfaith dialogue",
  "Islamic parenting advice",
  "Islamic law and jurisprudence",
  "Islamic social justice",
  "Islamic music and nasheeds",
  "Islamic homeschooling",
  "Islamic community events",
  "Islamic art and calligraphy",
  "Islamic travel experiences",
  "Islamic fitness and sports",
  "Islamic spirituality guidance",
  "Islamic media reviews",
  "Islamic podcast recommendations",
  "Islamic social projects",
  "Islamic online courses",
  "Islamic family values",
  "Islamic health tips",
  "Islamic literature recommendations",
  "Islamic parenting support groups",
  "Islamic finance tips and advice",
  "Islamic marriage counseling",
  "Islamic fashion trends",
  "Islamic business opportunities",
  "Islamic art exhibitions",
  "Islamic cooking tutorials",
  "Islamic women's rights discussions",
  "Islamic environmental initiatives",
  "Islamic language exchange programs",
  "Islamic community outreach",
  "Islamic lecture series",
  "Islamic history documentaries",
  "Islamic charity fundraising",
  "Islamic youth empowerment programs",
  "Islamic political discussions",
  "Islamic activism campaigns",
  "Islamic research papers",
  "Islamic community building strategies",
  "Islamic food blogs",
  "Islamic women's empowerment stories",
  "Islamic travel recommendations",
  "Islamic fitness challenges",
  "Islamic spirituality retreats"
]