query GetPosts ($username:String!,$query:NewsFeedQueryArgs!,$option:GetFeedDto!) {
getPosts(username: $username,query:$query,option: $option) {
    docs{
      author{
        avatar
        username
        email
        id
        name
      }
      commentsCount
      content
      createdAt
      id
      isLiked
      isOwnPost
      likesCount
      photos
      updatedAt
    }
    __typename
   next
    
  }
}