query me {
  me {
    avatar{
      avatarUrl
      avatarPublicId
    }
    username
    name
    email
    coverPicture{
      coverUrl
      coverPublicId
    }
    _id
    bio
    birthday
    contact
    gender
  }
}
