query UserProfile($username: String!) {
  user(username: $username) {
    username
    name
    avatar
    coverPicture
    bio
    birthday
    contact
    gender
    name
    email
    followersCount
    followingCount
    id
    isFollowing
    __typename
  }
}
