query UserProfile ($username: String!){
  user(username: $username){
    username
    name
    avatar
    coverPicture
    info{
      bio
      birthday
      contact
      gender
    }
    name
    dateJoined
    email
    followersCount
    followingCount
    id
    isFollowing
    __typename
  }
}
