query GetFollowing($options: PaginateOptionArgs!, $query: FollowQueryArgs!) {
  getFollowing(option: $options, query: $query) {
    avatar
    email
    id
    isFollowing
    name
    username
    contact
    birthday
    bio
    gender
    __typename
  }
}
